@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@baseUrl = {{protocol}}://{{domainname}}:{{port}}

### GET /games
GET {{baseUrl}}/games



### GET /games/:id
GET {{baseUrl}}/games/5

### GET /adverts
GET {{baseUrl}}/api/adverts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicHNldWRvIjoiemh6dGh0cmh6IiwiaWF0IjoxNjE1MzM4OTkzLCJleHAiOjE2MTUzNDI1OTN9.61mIQQA9XunbfRnjop0dyvNySwZp4cz9jbDV7HfXz3I

### GET /api/adverts/:id
GET {{baseUrl}}/api/adverts/3

### POST /login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "firstname": "Barack ",
    "lastname": "Obama"
}

### POST /login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "email": "mathis.dev@gmail.com",
    "password": "7890"
    
}

### URL encoded (le format par défaut pour les formulaires)
### ATTENTION : ne marche pas pour cette application

### POST /signin
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
    "firstname":"Mathis",
    "lastname":"SecretLeadDev",
    "pseudo":"Thismadu59",
    "email": "mathis.dev@gmail.com",
    "password": "7890",
    "phoneNumber":"0314597689",
    "localisationId": 2
}

### POST /cities

POST {{baseUrl}}/api/cities
Content-Type: application/json

{
    "city": "lyo"
}

### GET /api/test/27
GET {{baseUrl}}/api/test/27

### POST /api/create-advert

POST {{baseUrl}}/api/create-advert

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsInBzZXVkbyI6IlRoaXNtYWR1NTkiLCJpYXQiOjE2MTUzNzEzODIsImV4cCI6MTYxNTM3NDk4Mn0.GIDf0kaPn12n7HRbz-neCWMnIp85ScNr4cVF3cD7adY
Content-Type: 'application/json'

{
    "title": "Location de SevenWonders",
    "description": "je loue 7Wonders , je me suis trompé",
    "locationPrice": "10.00",
    "advertImage": "/home/etudiant/Bureau/images/7-wonders-vf.jpg", 
    "gameTitle": "Seven Wonders",
    "gameAuthor": "Antoine Bauza",
    "gameReleaseYear": "2010",
    "gameAvgDuration": "40-90 minutes",
    "gameMinPlayers": 2,
    "gameMaxPlayers": 7,
    "gameSuggestedAge": 10,
    "gameLocalisationId": 4,
    "gameId": ,
    "categories":[
        {"id" : 1},
        {"id" : 6}
    ]
}

